/*
SQLyog Ultimate v12.4.1 (64 bit)
MySQL - 11.5.2-MariaDB : Database - drunkcards
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`drunkcards` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;

USE `drunkcards`;

/*Table structure for table `admins` */

DROP TABLE IF EXISTS `admins`;

CREATE TABLE `admins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

/*Data for the table `admins` */

insert  into `admins`(`id`,`username`,`password`) values 
(1,'admin','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');

/*Table structure for table `cards` */

DROP TABLE IF EXISTS `cards`;

CREATE TABLE `cards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` text NOT NULL,
  `category` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=761 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

/*Data for the table `cards` */

insert  into `cards`(`id`,`question`,`category`) values 
(461,'Sino ang huling sinabihan mo ng \"I love you\" pero hindi mo naman talaga mahal?','drunk question'),
(462,'Anong pinaka-nakakahiyang chat na na-send mo nung lasing ka?','drunk question'),
(463,'Kung bibigyan ka ng 10k ngayon kapalit ng pag-text sa ex mo, gagawin mo ba?','drunk question'),
(464,'Sino sa mga nandito ang tingin mo ay \"red flag\"?','drunk question'),
(465,'Ano ang pinaka-malalang \"marupok\" moment mo?','drunk question'),
(466,'Kung magiging hayop ka pag lasing, ano ka?','drunk question'),
(467,'Sino ang \"TOTGA\" (The One That Got Away) mo at bakit?','drunk question'),
(468,'Anong lie ang sinabi mo para lang makauwi o maka-alis sa gala?','drunk question'),
(469,'Sino dito sa room ang huling tiningnan mo sa IG stories?','drunk question'),
(470,'Naranasan mo na bang umiyak sa CR habang may party sa labas?','drunk question'),
(471,'Sino sa atin ang feeling mo ay may hidden feelings sa isa pang tao dito?','drunk question'),
(472,'Kung may pagkakataon kang burahin ang isang ex sa memory mo, sino yun?','drunk question'),
(473,'Ano ang kanta na hinding-hindi mo mapakinggan nang hindi nalulungkot?','drunk question'),
(474,'Naranasan mo na bang mag-send ng \"I miss you\" tapos binura mo rin agad (unsend)?','drunk question'),
(475,'Sino ang huling taong ni-restrict mo sa Messenger?','drunk question'),
(476,'Anong pinaka-malalang nagawa mo para lang makaganti sa nanakit sa’yo?','drunk question'),
(477,'Naka-move on ka na ba talaga o pagod ka lang mag-isip?','drunk question'),
(478,'Sino dito ang pinaka-ayaw mong maging partner sa buhay?','drunk question'),
(479,'Ano ang huling bagay na hiniram mo pero hindi mo na binalik?','drunk question'),
(480,'Sino ang huling taong iniyakan mo dahil sa sobrang inis?','drunk question'),
(481,'Kung bibigyan ka ng chance na baguhin ang nakaraan, anong desisyon ang babaguhin mo?','drunk question'),
(482,'Sino ang taong pilit mong kinakalimutan pero laging nasa panaginip mo?','drunk question'),
(483,'Naranasan mo na bang maging \"kabit\" o \"the other person\"?','drunk question'),
(484,'Sino ang huling taong in-unfriend mo sa FB?','drunk question'),
(485,'Ano ang pinaka-weird na dahilan ng break-up niyo ng ex mo?','drunk question'),
(486,'Nakipag-balikan ka na ba sa taong niloko ka na dati?','drunk question'),
(487,'Anong trait mo ang pinaka-toxic na hindi mo maamin sa sarili mo?','drunk question'),
(488,'Sino dito ang huling in-stalk mo sa social media?','drunk question'),
(489,'Ano ang \"common lie\" na sinasabi mo sa mga magulang mo?','drunk question'),
(490,'Sino ang pinaka-fake na taong kilala mo?','drunk question'),
(491,'Naranasan mo na bang mag-pretend na lasing para lang makapagsabi ng totoo?','drunk question'),
(492,'Sino ang huling taong nagpa-kilig sa’yo na hindi mo naman dapat maging crush?','drunk question'),
(493,'Anong pinaka-pangit na compliment ang natanggap mo?','drunk question'),
(494,'Sino ang huling taong dinelete mo ang thread sa Messenger?','drunk question'),
(495,'Naranasan mo na bang mag-chat sa maling tao tungkol sa taong ka-chat mo rin?','drunk question'),
(496,'Sino ang huling pinag-selosan mo nang sobra?','drunk question'),
(497,'Anong kanta ang gusto mong patugtugin sa burol mo?','drunk question'),
(498,'Naranasan mo na bang ma-reject sa harap ng maraming tao?','drunk question'),
(499,'Sino ang huling taong nagpa-feel sa’yo na hindi ka sapat?','drunk question'),
(500,'Anong pinaka-malalang thing ang nagawa mo nung brokenhearted ka?','drunk question'),
(501,'Sino dito ang sa tingin mo ay hinding-hindi magiging loyal sa partner?','drunk question'),
(502,'Ano ang pinaka-selfish na bagay na nagawa mo?','drunk question'),
(503,'Sino ang taong gusto mong sampalin ngayon kung legal lang?','drunk question'),
(504,'Naranasan mo na bang mag-CR sa kung saan-saan dahil sa sobrang lasing?','drunk question'),
(505,'Sino ang huling taong nag-seen sa’yo na hanggang ngayon masakit pa rin?','drunk question'),
(506,'Anong pinaka-maling akala ng mga tao tungkol sa’yo?','drunk question'),
(507,'Sino ang taong pinaka-importante sa’yo pero hindi mo mapakita sa kanila?','drunk question'),
(508,'Ano ang huling \"red flag\" na binalewala mo?','drunk question'),
(509,'Sino ang huling taong napanaginipan mo sa weird na paraan?','drunk question'),
(510,'Naranasan mo na bang mag-check ng phone ng partner mo nang hindi niya alam?','drunk question'),
(511,'Sino ang huling sinabihan mo ng sikreto pero pinagsisihan mo?','drunk question'),
(512,'Anong huling kanta ang pinakinggan mo habang umiiyak?','drunk question'),
(513,'Sino dito ang pinaka-liking maging single habambuhay?','drunk question'),
(514,'Ano ang pinaka-mahal na binili mo na hindi mo naman talaga kailangan?','drunk question'),
(515,'Sino ang huling taong nag-comfort sa’yo nung down ka?','drunk question'),
(516,'Naranasan mo na bang maging \"third wheel\" na labas sa ilong ang ngiti?','drunk question'),
(517,'Sino ang huling taong nag-aya sa’yo ng date na tinanggihan mo?','drunk question'),
(518,'Anong pinaka-pangit na ugali ng ex mo ang meron ka rin?','drunk question'),
(519,'Sino ang huling taong nag-send sa’yo ng voice message?','drunk question'),
(520,'Naranasan mo na bang ma-ghost at mang-ghost?','drunk question'),
(521,'Sino ang huling taong pinag-dasal mo?','drunk question'),
(522,'Ano ang pinaka-malalang rejection na natanggap mo sa trabaho o school?','drunk question'),
(523,'Sino ang huling taong hiningan mo ng validation?','drunk question'),
(524,'Naranasan mo na bang mag-kunwari na wala ka sa bahay para lang iwasan ang bisita?','drunk question'),
(525,'Sino ang huling taong nag-paramdam sa’yo na special ka?','drunk question'),
(526,'Anong pinaka-mahabang oras na wala kang ligo dahil sa lungkot?','drunk question'),
(527,'Sino ang huling taong naging dahilan ng stress mo?','drunk question'),
(528,'Naranasan mo na bang mag-comment sa post ng ex mo tapos binura mo rin?','drunk question'),
(529,'Sino ang huling taong in-ignore mo ang tawag?','drunk question'),
(530,'Anong pinaka-mahirap na part ng pagiging ikaw?','drunk question'),
(531,'Sino ang huling taong sinabihan mo ng \"Sana hindi na lang tayo nag-meet\"?','drunk question'),
(532,'Naranasan mo na bang magmahal ng dalawang tao sa parehong pagkakataon?','drunk question'),
(533,'Sino ang huling taong nagpa-smile sa’yo ngayong araw?','drunk question'),
(534,'Anong pinaka-matagal na time na hindi ka nag-toothbrush dahil sa depression?','drunk question'),
(535,'Sino ang huling taong inabutan mo ng pera kahit wala ka na ring pera?','drunk question'),
(536,'Naranasan mo na bang mag-walkout sa isang date?','drunk question'),
(537,'Sino ang huling taong nag-disappoint sa’yo nang sobra?','drunk question'),
(538,'Anong pinaka-malalang rumor ang narinig mo tungkol sa’yo?','drunk question'),
(539,'Sino ang huling taong niyakap mo nang matagal?','drunk question'),
(540,'Naranasan mo na bang mag-selfie habang umiiyak?','drunk question'),
(541,'Sino ang huling taong hiningan mo ng seryosong advice?','drunk question'),
(542,'Anong pinaka-mahal na pagkakamali ang nagawa mo sa buhay?','drunk question'),
(543,'Sino ang huling taong tinawagan mo nung lasing ka?','drunk question'),
(544,'Naranasan mo na bang mag-deny ng feelings dahil sa takot?','drunk question'),
(545,'Sino ang huling taong nag-block sa’yo?','drunk question'),
(546,'Anong pinaka-malalang \"drunk call\" na nagawa mo?','drunk question'),
(547,'Sino ang huling taong naging inspiration mo para mag-improve?','drunk question'),
(548,'Naranasan mo na bang mag-stay sa isang toxic relationship para lang sa physical attraction?','drunk question'),
(549,'Sino ang huling taong sinabihan mo ng \"Kaya mo yan\" pero alam mong mahirap?','drunk question'),
(550,'Anong pinaka-malungkot na kanta sa playlist mo?','drunk question'),
(551,'Sino ang huling taong naging dahilan ng \"relapse\" mo?','drunk question'),
(552,'Naranasan mo na bang mag-sinungaling sa therapist o kaibigan?','drunk question'),
(553,'Sino ang huling taong sinabihan mo ng \"Miss na kita\" pero hindi totoo?','drunk question'),
(554,'Anong pinaka-malalang trait na nakuha mo sa parents mo?','drunk question'),
(555,'Sino ang huling taong pinaramdam sa’yo na hindi ka priority?','drunk question'),
(556,'Naranasan mo na bang mag-shopping para lang makalimot sa problema?','drunk question'),
(557,'Sino ang huling taong naging \"home\" mo?','drunk question'),
(558,'Anong pinaka-malalang thing ang nasabi mo sa taong mahal mo nung galit ka?','drunk question'),
(559,'Sino ang huling taong binigyan mo ng chance pero sinayang pa rin?','drunk question'),
(560,'Kung kailangan mong pumili ng isa sa room na ito para iligtas sa sunog, sino yun?','drunk question'),
(561,'If I was a season, anong season ako para sa’yo?','comfort question'),
(562,'Anong core memory natin ang hinding-hindi mo malilimutan?','comfort question'),
(563,'Saang lugar ka pinaka-kalmado?','comfort question'),
(564,'Anong trait ko ang nakakapag-pagaan ng loob mo?','comfort question'),
(565,'If you could see yourself through my eyes, ano ang tingin mo sa sarili mo?','comfort question'),
(566,'Anong kanta ang gusto mong patugtugin ko kapag malungkot ka?','comfort question'),
(567,'Ano ang \"love language\" mo na madalas hindi naiintindihan ng iba?','comfort question'),
(568,'Kung magiging bulaklak ako, anong klase ako at bakit?','comfort question'),
(569,'Anong advice ang ibibigay mo sa 10-year-old self mo?','comfort question'),
(570,'Ano ang pinaka-proud accomplishment mo na hindi alam ng marami?','comfort question'),
(571,'Sino ang taong tinatawagan mo kapag pagod ka na sa mundo?','comfort question'),
(572,'Ano ang definition mo ng \"home\"?','comfort question'),
(573,'Kung magiging kulay ako, anong kulay ko base sa personality ko?','comfort question'),
(574,'Ano ang pinaka-sweet na bagay na ginawa ng isang tao para sa’yo?','comfort question'),
(575,'Anong movie ang paborito mong panoorin pag gusto mong mag-relax?','comfort question'),
(576,'Ano ang dream life mo 5 years from now?','comfort question'),
(577,'Paano mo gustong i-comfort ka kapag pagod ka sa work/school?','comfort question'),
(578,'Ano ang favorite physical feature mo sa sarili mo?','comfort question'),
(579,'Kung magiging weather ako, anong klaseng panahon ako?','comfort question'),
(580,'Ano ang message mo sa taong pinaka-miss mo ngayon?','comfort question'),
(581,'Ano ang pinaka-unang thing na napansin mo nung nag-meet tayo?','comfort question'),
(582,'Anong amoy ang nagpapa-alala sa’yo ng pagkabata?','comfort question'),
(583,'Kung magiging element ako (Earth, Air, Fire, Water), ano ako?','comfort question'),
(584,'Ano ang pinaka-mahalagang lesson na natutunan mo sa isang heartbreak?','comfort question'),
(585,'Anong klaseng pagmamahal ang tingin mong deserve mo?','comfort question'),
(586,'Ano ang paborito mong part ng araw (Umaga, Hapon, Gabi)?','comfort question'),
(587,'Kung magiging instrument ako, anong tunog ko?','comfort question'),
(588,'Ano ang pinaka-safe na memory mo?','comfort question'),
(589,'Anong \"small win\" mo ngayong linggo na gusto mong i-celebrate natin?','comfort question'),
(590,'Kung magiging libro ako, anong genre ko?','comfort question'),
(591,'Ano ang pinaka-magandang sinabi ng isang tao tungkol sa personality mo?','comfort question'),
(592,'Paano ka nag-heal mula sa pinaka-mahirap na moment sa buhay mo?','comfort question'),
(593,'Ano ang paborito mong comfort food tuwing umuulan?','comfort question'),
(594,'Kung magiging bituin ako, saang constellation ako?','comfort question'),
(595,'Ano ang pinaka-meaningful na gift na natanggap mo na walang presyo?','comfort question'),
(596,'Sino ang hero mo sa totoong buhay?','comfort question'),
(597,'Anong hobby ang nakakapag-pa-feel sa’yo na alive ka?','comfort question'),
(598,'Kung magiging tula ako, tungkol saan ako?','comfort question'),
(599,'Ano ang gusto mong sabihin sa sarili mo sa future?','comfort question'),
(600,'Anong trait ng parents mo ang gusto mong ipasa sa mga anak mo?','comfort question'),
(601,'Kung magiging kalsada ako, saan ako papunta?','comfort question'),
(602,'Ano ang pinaka-payapang panaginip na naranasan mo?','comfort question'),
(603,'Anong salita ang pinaka-paborito mong marinig?','comfort question'),
(604,'Kung magiging prutas ako, gaano ako katamis o ka-asim?','comfort question'),
(605,'Ano ang pinaka-unang thing na gagawin mo pag naging milyonaryo ka?','comfort question'),
(606,'Sino ang huling taong nagpa-iyak sa’yo sa tuwa?','comfort question'),
(607,'Anong quote ang pinanghahawakan mo tuwing nahihirapan ka?','comfort question'),
(608,'Kung magiging planet ako, alin ako sa solar system?','comfort question'),
(609,'Ano ang pinaka-unang memory mo noong bata ka pa?','comfort question'),
(610,'Anong part ng bahay ang pinaka-favorite mo?','comfort question'),
(611,'Kung magiging alon ako sa dagat, gaano ako kalakas?','comfort question'),
(612,'Ano ang pinaka-honest na description mo sa akin?','comfort question'),
(613,'Sino ang taong hinding-hindi mo kayang tiisin?','comfort question'),
(614,'Anong bagay ang nagpapa-smile sa’yo kahit gaano kapangit ang araw mo?','comfort question'),
(615,'Kung magiging kanta ako, anong lyrics ang uuliting mo?','comfort question'),
(616,'Ano ang pinaka-unang thing na gusto mong gawin pag-gising sa umaga?','comfort question'),
(617,'Sino ang taong nag-impluwensya sa’yo para maging mabuting tao?','comfort question'),
(618,'Anong trait mo ang pinaka-nagustuhan mo sa sarili mo kamakailan?','comfort question'),
(619,'Kung magiging panaginip ako, anong klaseng panaginip ako?','comfort question'),
(620,'Ano ang pinaka-unang thing na napansin mo sa akin nung una tayong nag-usap?','comfort question'),
(621,'Sino ang taong gusto mong pasalamatan pero hindi mo magawa?','comfort question'),
(622,'Anong memory ang gusto mong i-keep forever?','comfort question'),
(623,'Kung magiging painting ako, anong colors ang gagamitin?','comfort question'),
(624,'Ano ang pinaka-importante sa’yo: Trust o Loyalty?','comfort question'),
(625,'Anong \"ugly truth\" ang tinanggap mo na tungkol sa buhay?','comfort question'),
(626,'Sino ang taong nakakaalam ng lahat tungkol sa’yo?','comfort question'),
(627,'Anong kanta ang gusto mong i-alay sa akin?','comfort question'),
(628,'Kung magiging boses ako, anong emosyon ang dala ko?','comfort question'),
(629,'Ano ang pinaka-unang dream job mo nung bata ka?','comfort question'),
(630,'Sino ang taong pinaka-pinagkakatiwalaan mo sa lahat?','comfort question'),
(631,'Anong lesson ang itinuro sa’yo ng pinaka-mahirap mong downfall?','comfort question'),
(632,'Kung magiging hayop ako sa dagat, ano ako?','comfort question'),
(633,'Ano ang pinaka-magandang sunrise/sunset na nakita mo?','comfort question'),
(634,'Sino ang taong nagpapatawa sa’yo kahit seryoso ang sitwasyon?','comfort question'),
(635,'Anong trait ko ang pinaka-paborito mo?','comfort question'),
(636,'Kung magiging star ako, gaano ako kaningning?','comfort question'),
(637,'Ano ang pinaka-payapang sound para sa’yo?','comfort question'),
(638,'Sino ang taong laging nandiyan para sa’yo kahit hindi mo hingin?','comfort question'),
(639,'Anong bagay ang nagpapa-alala sa’yo na \"everything will be okay\"?','comfort question'),
(640,'Kung magiging scent ako, anong memory ang naaalala mo?','comfort question'),
(641,'Ano ang pinaka-magandang realization mo ngayong taon?','comfort question'),
(642,'Sino ang taong gusto mong makasama sa pagtanda?','comfort question'),
(643,'Anong hobby ang nakakapag-pawala ng stress mo?','comfort question'),
(644,'Kung magiging garden ako, anong klaseng flowers ang nandoon?','comfort question'),
(645,'Ano ang pinaka-unang thing na na-appreciate mo sa akin?','comfort question'),
(646,'Sino ang taong laging nakikinig sa mga rants mo?','comfort question'),
(647,'Anong kanta ang nagpapa-alala sa’yo ng \"safe space\" mo?','comfort question'),
(648,'Kung magiging pelikula ang buhay mo, ano ang ending?','comfort question'),
(649,'Ano ang pinaka-meaningful na turo ng lolo/lola mo sa’yo?','comfort question'),
(650,'Sino ang taong nagpabago ng pananaw mo sa pag-ibig?','comfort question'),
(651,'Anong trait mo ang gusto mong hindi magbago kahit kailan?','comfort question'),
(652,'Kung magiging isla ako, anong adventure ang nandoon?','comfort question'),
(653,'Ano ang pinaka-proud accomplishment mo sa personality mo?','comfort question'),
(654,'Sino ang taong hinding-hindi mo malilimutan kahit lumipas ang panahon?','comfort question'),
(655,'Anong bagay ang nagpapa-alala sa’yo na mahalaga ka?','comfort question'),
(656,'Kung magiging hangin ako, anong lamig o init ko?','comfort question'),
(657,'Ano ang pinaka-unang thing na sasabihin mo sa akin pag nagkita tayo uli?','comfort question'),
(658,'Sino ang taong nagpapa-feel sa’yo na normal lang maging hindi okay?','comfort question'),
(659,'Anong lesson ang gusto mong ituro sa susunod na generation?','comfort question'),
(660,'Kung magiging universe ako, anong galaxy ako?','comfort question'),
(661,'Ano ang biggest turn-on mo sa isang partner?','+18 adults question'),
(662,'Anong part ng body mo ang pinaka-sensitive?','+18 adults question'),
(663,'Do you prefer being the \"boss\" or being \"submissive\"?','+18 adults question'),
(664,'Ano ang pinaka-matagal na \"session\" na naranasan mo?','+18 adults question'),
(665,'Naranasan mo na bang makipag-hookup sa strangers?','+18 adults question'),
(666,'Ano ang favorite position mo at bakit?','+18 adults question'),
(667,'Have you ever had a crush sa friend ng partner mo?','+18 adults question'),
(668,'Anong outfit ang tingin mo ay pinaka-sexy sa isang tao?','+18 adults question'),
(669,'Ano ang opinion mo sa \"friends with benefits\"?','+18 adults question'),
(670,'Napanood mo na ba ang partner mo habang may ginagawa silang solo?','+18 adults question'),
(671,'Ano ang pinaka-wild na place na gusto mong subukan?','+18 adults question'),
(672,'Gaano ka-importante ang \"size\" para sa’yo?','+18 adults question'),
(673,'Ano ang pinaka-kakaibang \"kink\" na narinig o nasubukan mo?','+18 adults question'),
(674,'Morning sex o Midnight sex?','+18 adults question'),
(675,'Ano ang reaksyon mo kapag may nakakita sa inyo habang gumagawa?','+18 adults question'),
(676,'Ano ang pinaka-mahal na binayaran mo para sa pleasure?','+18 adults question'),
(677,'Naranasan mo na bang magkaroon ng \"one night stand\"?','+18 adults question'),
(678,'Ano ang pinaka-dirty na text na na-receive mo?','+18 adults question'),
(679,'Sino ang huling taong napanaginipan mo sa malisyang paraan?','+18 adults question'),
(680,'Anong \"toy\" ang gusto mong subukan o paborito mo?','+18 adults question'),
(681,'Naranasan mo na bang gawin ito sa loob ng sinehan?','+18 adults question'),
(682,'Ano ang pinaka-matagal na \"foreplay\" na naranasan mo?','+18 adults question'),
(683,'Sino sa mga kakilala mo ang \"sex god/goddess\" sa tingin mo?','+18 adults question'),
(684,'Ano ang pinaka-unang thing na tinitingnan mo sa katawan ng kabilang gender?','+18 adults question'),
(685,'Naranasan mo na bang mag-send ng \"nudes\" sa maling tao?','+18 adults question'),
(686,'Ano ang opinion mo sa \"aftercare\"?','+18 adults question'),
(687,'Anong age mo nung nawala ang \"V-card\" mo?','+18 adults question'),
(688,'Prefer mo ba ang may \"music\" habang ginagawa o silence?','+18 adults question'),
(689,'Ano ang pinaka-wild na thing na sinabi mo habang nasa \"act\"?','+18 adults question'),
(690,'Naka-experience ka na ba ng \"threesome\"? Gusto mo ba?','+18 adults question'),
(691,'Ano ang pinaka-weird na turn-on para sa’yo?','+18 adults question'),
(692,'Loud o Quiet? Anong mas gusto mo?','+18 adults question'),
(693,'Ano ang pinaka-unang thing na pumasok sa isip mo nung unang beses mong ginawa?','+18 adults question'),
(694,'Sino ang \"celebrity hall pass\" mo?','+18 adults question'),
(695,'Naranasan mo na bang makipag-do sa opisina o school?','+18 adults question'),
(696,'Ano ang pinaka-sexy na accent para sa’yo?','+18 adults question'),
(697,'Dirty talk o Romantic whispers?','+18 adults question'),
(698,'Ano ang huling \"adult film\" na napanood mo?','+18 adults question'),
(699,'Naranasan mo na bang mag-record ng \"video\" habang ginagawa?','+18 adults question'),
(700,'Ano ang pinaka-wild na dare na ginawa mo sa isang \"spin the bottle\" game?','+18 adults question'),
(701,'Have you ever used food in bed? Ano yun?','+18 adults question'),
(702,'Shower sex: Overrated o Underrated?','+18 adults question'),
(703,'Ano ang pinaka-unang thing na gusto mong gawin sa akin sa isang hotel room?','+18 adults question'),
(704,'Sino sa mga ex mo ang pinaka-magaling sa kama?','+18 adults question'),
(705,'Naranasan mo na bang ma-caught in the act ng parents mo?','+18 adults question'),
(706,'Anong body part ng partner mo ang paborito mong halikan?','+18 adults question'),
(707,'Ano ang longest \"drought\" (walang sex) na naranasan mo?','+18 adults question'),
(708,'Naranasan mo na bang makipag-do sa car habang umaandar?','+18 adults question'),
(709,'Ano ang opinion mo sa \"roleplay\"?','+18 adults question'),
(710,'Sino ang pinaka-recent na taong gusto mong makasama sa kama?','+18 adults question'),
(711,'Ano ang pinaka-unang thing na ginagawa mo pagka-tapos ng \"act\"?','+18 adults question'),
(712,'Naranasan mo na bang gumamit ng \"ice\" sa bed?','+18 adults question'),
(713,'Ano ang pinaka-grabe na \"hickey\" (chupa) na nakuha mo at saan?','+18 adults question'),
(714,'Prefer mo ba ang \"shaved\" o \"natural\"?','+18 adults question'),
(715,'Ano ang pinaka-dirty na thing na naisip mo ngayong araw?','+18 adults question'),
(716,'Naranasan mo na bang makipag-hookup sa friend ng ex mo?','+18 adults question'),
(717,'Ano ang opinion mo sa \"open relationship\"?','+18 adults question'),
(718,'Sino ang \"work crush\" mo na gusto mong makasama sa kama?','+18 adults question'),
(719,'Ano ang pinaka-unang thing na napapansin mo sa underwear ng partner mo?','+18 adults question'),
(720,'Naranasan mo na bang mag-usap tungkol sa sex sa unang date?','+18 adults question'),
(721,'Ano ang pinaka-sexy na trait ng isang tao para sa’yo?','+18 adults question'),
(722,'Lights on o Lights off?','+18 adults question'),
(723,'Ano ang pinaka-unang thing na ginagawa mo pag gising na \"horny\"?','+18 adults question'),
(724,'Naranasan mo na bang ma-injure habang nag-se-sex?','+18 adults question'),
(725,'Ano ang pinaka-mahal na underwear na binili mo?','+18 adults question'),
(726,'Sino ang taong gusto mong \"tikman\" kahit bawal?','+18 adults question'),
(727,'Ano ang opinion mo sa \"sexting\"?','+18 adults question'),
(728,'Naranasan mo na bang mag-fake ng \"O\"?','+18 adults question'),
(729,'Ano ang pinaka-wild na fantasy mo na hindi mo pa nasasabi sa kahit kanino?','+18 adults question'),
(730,'Sino ang huling taong ni-search mo sa isang adult site?','+18 adults question'),
(731,'Ano ang pinaka-unang thing na gusto mong hawakan sa akin?','+18 adults question'),
(732,'Naranasan mo na bang makipag-do habang may ibang tao sa kabilang room?','+18 adults question'),
(733,'Ano ang pinaka-sexy na song para sa’yo?','+18 adults question'),
(734,'Blindfolded o Handcuffed? Alin ang mas okay?','+18 adults question'),
(735,'Ano ang pinaka-unang \"sex toy\" na nakita mo?','+18 adults question'),
(736,'Sino ang pinaka-wild na nakatabi mo sa kama?','+18 adults question'),
(737,'Ano ang opinion mo sa \"no strings attached\"?','+18 adults question'),
(738,'Naranasan mo na bang makipag-do sa public park?','+18 adults question'),
(739,'Ano ang pinaka-unang thing na na-imagine mong ginagawa natin?','+18 adults question'),
(740,'Sino ang huling taong nag-send sa’yo ng spicy pic?','+18 adults question'),
(741,'Ano ang pinaka-grabe na \"dirty talk\" na sinabi mo?','+18 adults question'),
(742,'Naranasan mo na bang makipag-sex sa pool o dagat?','+18 adults question'),
(743,'Ano ang opinion mo sa \"friends with benefits\" na naging real?','+18 adults question'),
(744,'Sino ang huling taong gusto mong makita nang walang damit?','+18 adults question'),
(745,'Ano ang pinaka-unang thing na gagawin mo pag na-lock tayo sa isang room?','+18 adults question'),
(746,'Naranasan mo na bang mag-send ng spicy pic sa group chat by mistake?','+18 adults question'),
(747,'Ano ang pinaka-weird na place na naisip mo para mag-sex?','+18 adults question'),
(748,'Sino ang huling taong nakita mong hubad (sa personal)?','+18 adults question'),
(749,'Ano ang opinion mo sa \"one night stands\" sa Tinder?','+18 adults question'),
(750,'Naranasan mo na bang makipag-do habang may music ng Disney?','+18 adults question'),
(751,'Ano ang pinaka-sexy na nickname na itinawag sa’yo?','+18 adults question'),
(752,'Sino ang huling taong gusto mong halikan sa leeg?','+18 adults question'),
(753,'Ano ang pinaka-wild na experience mo sa isang party?','+18 adults question'),
(754,'Naranasan mo na bang makipag-sex habang umuulan sa labas?','+18 adults question'),
(755,'Ano ang pinaka-unang thing na gusto mong dilaan?','+18 adults question'),
(756,'Sino ang huling taong naging \"booty call\" mo?','+18 adults question'),
(757,'Ano ang opinion mo sa \"morning wood\"?','+18 adults question'),
(758,'Naranasan mo na bang makipag-do sa beach?','+18 adults question'),
(759,'Ano ang pinaka-wild na thing na nagawa mo sa sarili mo?','+18 adults question'),
(760,'Sino ang huling taong gusto mong makasama sa isang \"no-holds-barred\" na gabi?','+18 adults question');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
